spring:
  cloud:
    stream:
      kafka:
        binder:
          brokers: broker-service
eureka:
  client:
    serviceUrl:
      defaultZone: http://discovery-server-service:8089/eureka/
  zipkin:
    base-url: http://zipkin-server-service:8090
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        temp:
          use_jdbc_metadata_defaults: false;
