POST http://localhost:8000/departments
Content-Type: application/json

{"name":  "training-test"}

###

GET http://localhost:8000/departments/4
Accept: application/json

###

POST http://localhost:8080/api/v1/departments/departments
Content-Type: application/json

{"name":  "training-test"}

###

GET http://localhost:8080/api/v1/departments/departments/1
Content-Type: application/json

###

POST http://localhost:8080/api/v1/users/users
Content-Type: application/json

{"firstName":  "Jan", "lastName": "Kowalski"}

###

POST http://localhost:8001/users
Content-Type: application/json

{"login":  "jan", "password": "123", "firstName":  "Jan", "lastName": "Kowalski"}

###

POST http://localhost:8001/oauth/token
Content-Type: application/x-www-form-urlencoded

username=jan&password=123&client_id=training&grant_type=password

###

GET http://localhost:8001/users/active
Accept: application/json
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHAiOjE1NjQ3ODAzMzgsInVzZXJfbmFtZSI6ImphbiIsImF1dGhvcml0aWVzIjpbIlJPTEVfVVNFUiJdLCJqdGkiOiJmNWZjYjMwYi0xMjY5LTQ3NzgtYjMzZS01OTYxZDFhZTE3Y2QiLCJjbGllbnRfaWQiOiJ0cmFpbmluZyIsInNjb3BlIjpbImFwaSJdfQ.JoriwLW_0-VKeNR3maHW3djSw3pJXcDT9ZY_l0lndxg

###

GET http://localhost:8001/users
Accept: application/json
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHAiOjE1NjQ3ODAzMzgsInVzZXJfbmFtZSI6ImphbiIsImF1dGhvcml0aWVzIjpbIlJPTEVfVVNFUiJdLCJqdGkiOiJmNWZjYjMwYi0xMjY5LTQ3NzgtYjMzZS01OTYxZDFhZTE3Y2QiLCJjbGllbnRfaWQiOiJ0cmFpbmluZyIsInNjb3BlIjpbImFwaSJdfQ.JoriwLW_0-VKeNR3maHW3djSw3pJXcDT9ZY_l0lndxg

###

GET http://localhost:8080/api/v1/users/users
Accept: application/json

###

POST http://localhost:8888/monitor
Content-Type: application/x-www-form-urlencoded

path=users

###

POST http://localhost:8888/encrypt

Spring cloud

###

POST http://localhost:8888/decrypt

8f5489fd9b9904e234eb51e27667584de44d5389cf737b743cc34a9ca612917c

###